version: '3.8'
services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: trade_user
      POSTGRES_PASSWORD: trade_pass
      POSTGRES_DB: trade_db
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  zookeeper:
    image: bitnamilegacy/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnamilegacy/kafka:3.5.1-debian-11-r0
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper


volumes:
  pgdata:
  mongodata:
